#!/bin/bash
# ============================================
# Medusa E-Commerce - One Command Deploy Script
# Run on your VPS: chmod +x deploy.sh && ./deploy.sh
# ============================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

print_step() { echo -e "${CYAN}[STEP]${NC} $1"; }
print_ok() { echo -e "${GREEN}[OK]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_err() { echo -e "${RED}[ERROR]${NC} $1"; }

echo ""
echo "=========================================="
echo "  Medusa E-Commerce - VPS Deploy Script"
echo "  Optimized for 1-core / 4GB RAM"
echo "=========================================="
echo ""

# ---------- Check if running as root ----------
if [ "$EUID" -ne 0 ]; then
    print_err "Please run as root: sudo ./deploy.sh"
    exit 1
fi

# ---------- Get domain from user ----------
if [ -z "$1" ]; then
    read -p "Enter your domain name (e.g., mystore.com): " DOMAIN
else
    DOMAIN=$1
fi

if [ -z "$DOMAIN" ]; then
    print_err "Domain name is required!"
    exit 1
fi

read -p "Enter admin email (for SSL & admin account): " ADMIN_EMAIL
if [ -z "$ADMIN_EMAIL" ]; then
    ADMIN_EMAIL="admin@${DOMAIN}"
fi

read -sp "Enter admin password: " ADMIN_PASSWORD
echo ""
if [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD="supersecret123"
    print_warn "Using default admin password. Change it after first login!"
fi

echo ""
print_step "Domain: ${DOMAIN}"
print_step "Admin Email: ${ADMIN_EMAIL}"
echo ""

# ============================================
# STEP 1: Install Docker
# ============================================
print_step "1/8 - Installing Docker..."

if command -v docker &> /dev/null; then
    print_ok "Docker already installed: $(docker --version)"
else
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    print_ok "Docker installed successfully"
fi

# Ensure docker compose plugin
if ! docker compose version &> /dev/null; then
    apt-get update && apt-get install -y docker-compose-plugin
fi
print_ok "Docker Compose: $(docker compose version)"

# ============================================
# STEP 2: Create swap (safety net for 4GB RAM)
# ============================================
print_step "2/8 - Setting up 2GB swap file..."

if [ ! -f /swapfile ]; then
    fallocate -l 2G /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo '/swapfile none swap sw 0 0' >> /etc/fstab
    # Optimize swap for low-RAM server
    sysctl vm.swappiness=10
    echo 'vm.swappiness=10' >> /etc/sysctl.conf
    print_ok "2GB swap created"
else
    print_ok "Swap already exists"
fi

# ============================================
# STEP 3: Generate secrets
# ============================================
print_step "3/8 - Generating secrets..."

JWT_SECRET=$(openssl rand -hex 32)
COOKIE_SECRET=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 16)
REVALIDATE_SECRET=$(openssl rand -hex 16)

print_ok "Secrets generated"

# ============================================
# STEP 4: Create .env file
# ============================================
print_step "4/8 - Creating environment config..."

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

cat > .env << ENVEOF
# Auto-generated by deploy.sh on $(date)
DOMAIN=${DOMAIN}
ADMIN_EMAIL=${ADMIN_EMAIL}

# Database
POSTGRES_USER=medusa
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=medusa_db
DATABASE_URL=postgres://medusa:${POSTGRES_PASSWORD}@postgres:5432/medusa_db

# Redis
REDIS_URL=redis://redis:6379

# Secrets
JWT_SECRET=${JWT_SECRET}
COOKIE_SECRET=${COOKIE_SECRET}

# CORS
STORE_CORS=https://${DOMAIN}
ADMIN_CORS=https://${DOMAIN}
AUTH_CORS=https://${DOMAIN}

# Medusa
MEDUSA_BACKEND_URL=https://${DOMAIN}
MEDUSA_WORKER_MODE=shared
PORT=9000

# Storefront
NEXT_PUBLIC_MEDUSA_BACKEND_URL=https://${DOMAIN}
NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=temp_will_update_after_setup
NEXT_PUBLIC_DEFAULT_REGION=us
REVALIDATE_SECRET=${REVALIDATE_SECRET}

# SSL
ACME_EMAIL=${ADMIN_EMAIL}
ENVEOF

print_ok ".env file created"

# ============================================
# STEP 5: Update Nginx config with domain
# ============================================
print_step "5/8 - Configuring Nginx for ${DOMAIN}..."

sed -i "s/DOMAIN_PLACEHOLDER/${DOMAIN}/g" nginx/conf.d/default.conf
print_ok "Nginx configured for ${DOMAIN}"

# ============================================
# STEP 6: Clone Medusa backend & storefront
# ============================================
print_step "6/8 - Setting up Medusa backend & storefront..."

# Clone Medusa backend if empty
if [ ! -f backend/package.json ]; then
    print_step "Scaffolding Medusa backend..."
    # Create a temp medusa app and copy backend files
    npx --yes create-medusa-app@latest temp-medusa --skip-db --no-browser --directory temp-medusa -y 2>/dev/null || true

    if [ -d "temp-medusa" ]; then
        cp -r temp-medusa/* backend/ 2>/dev/null || true
        cp -r temp-medusa/.* backend/ 2>/dev/null || true
        rm -rf temp-medusa
        print_ok "Medusa backend scaffolded"
    else
        # Fallback: init manually
        cd backend
        npm init -y
        npm install @medusajs/medusa@latest @medusajs/framework@latest
        cd "$SCRIPT_DIR"
        print_ok "Medusa backend initialized manually"
    fi
fi

# Clone storefront if empty
if [ ! -f storefront/package.json ]; then
    print_step "Cloning Next.js storefront..."
    git clone https://github.com/medusajs/nextjs-starter-medusa.git temp-storefront
    cp -r temp-storefront/* storefront/ 2>/dev/null || true
    cp -r temp-storefront/.* storefront/ 2>/dev/null || true
    rm -rf temp-storefront

    # Configure standalone output for Docker
    if [ -f storefront/next.config.js ]; then
        # Add output: 'standalone' if not present
        grep -q "output:" storefront/next.config.js || \
            sed -i 's/const nextConfig = {/const nextConfig = {\n  output: "standalone",/' storefront/next.config.js
    fi

    print_ok "Storefront cloned"
fi

# ============================================
# STEP 7: Build & Start with Docker Compose
# ============================================
print_step "7/8 - Building & starting services (this takes 3-5 min on 1 core)..."

docker compose down 2>/dev/null || true
docker compose build --no-cache
docker compose up -d

print_ok "All services starting..."

# Wait for Medusa to be healthy
print_step "Waiting for Medusa backend to be ready..."
MAX_WAIT=120
WAITED=0
until curl -sf http://localhost:9000/health > /dev/null 2>&1; do
    sleep 5
    WAITED=$((WAITED + 5))
    if [ $WAITED -ge $MAX_WAIT ]; then
        print_warn "Backend taking longer than expected. Check: docker compose logs medusa"
        break
    fi
    echo -n "."
done
echo ""
print_ok "Medusa backend is running!"

# Create admin user
print_step "Creating admin user..."
docker compose exec -T medusa npx medusa user -e "${ADMIN_EMAIL}" -p "${ADMIN_PASSWORD}" 2>/dev/null || \
    print_warn "Admin user may already exist"

# ============================================
# STEP 8: SSL Setup
# ============================================
print_step "8/8 - Setting up SSL certificate..."

# Get SSL cert
docker compose run --rm certbot certonly \
    --webroot \
    --webroot-path=/var/www/certbot \
    --email "${ADMIN_EMAIL}" \
    --agree-tos \
    --no-eff-email \
    -d "${DOMAIN}" 2>/dev/null

if [ $? -eq 0 ]; then
    # Enable HTTPS in Nginx config
    cat > nginx/conf.d/default.conf << 'NGINXEOF'
# ============================================
# Nginx - HTTPS Enabled Config
# ============================================

upstream medusa_backend {
    server medusa:9000;
}

upstream storefront {
    server storefront:8000;
}

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name DOMAIN_REPLACE;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl http2;
    server_name DOMAIN_REPLACE;

    ssl_certificate /etc/letsencrypt/live/DOMAIN_REPLACE/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/DOMAIN_REPLACE/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Medusa Admin
    location /app {
        proxy_pass http://medusa_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Medusa API routes
    location /store {
        proxy_pass http://medusa_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin {
        proxy_pass http://medusa_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /auth {
        proxy_pass http://medusa_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /hooks {
        proxy_pass http://medusa_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /health {
        proxy_pass http://medusa_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Static assets (cached)
    location /_next/static {
        proxy_pass http://storefront;
        proxy_cache static_cache;
        proxy_cache_valid 200 60m;
        add_header X-Cache-Status $upstream_cache_status;
        expires 30d;
    }

    # Storefront (everything else)
    location / {
        proxy_pass http://storefront;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
NGINXEOF

    sed -i "s/DOMAIN_REPLACE/${DOMAIN}/g" nginx/conf.d/default.conf
    docker compose restart nginx
    print_ok "SSL enabled! Site live at https://${DOMAIN}"
else
    print_warn "SSL setup failed. Site available at http://${DOMAIN} (port 80)"
    print_warn "Run manually later: docker compose run --rm certbot certonly --webroot --webroot-path=/var/www/certbot -d ${DOMAIN}"
fi

# ============================================
# DONE!
# ============================================
echo ""
echo "=========================================="
echo -e "${GREEN}  DEPLOYMENT COMPLETE!${NC}"
echo "=========================================="
echo ""
echo "  Storefront:  https://${DOMAIN}"
echo "  Admin Panel:  https://${DOMAIN}/app"
echo "  Admin Login:  ${ADMIN_EMAIL}"
echo ""
echo "  Next steps:"
echo "  1. Login to admin at https://${DOMAIN}/app"
echo "  2. Create a region (Settings → Regions)"
echo "  3. Create a publishable API key (Settings → API Keys)"
echo "  4. Update .env: NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=your_key"
echo "  5. Rebuild storefront: docker compose up -d --build storefront"
echo "  6. Add your products!"
echo ""
echo "  Useful commands:"
echo "  - View logs:    docker compose logs -f"
echo "  - Stop:         docker compose down"
echo "  - Restart:      docker compose restart"
echo "  - Update:       git pull && docker compose up -d --build"
echo ""
